spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: misi1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # ddl-auto: create, create-drop, update, validate 중 선택
    show-sql: true  # SQL 쿼리 로그 출력 여부
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리 포맷팅
        use_sql_comments: true  # SQL 쿼리에서 주석 사용 여부
